import java.io.File;
import java.io.FileWriter;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class TextParser {

    public static void main(String[] args) {
        File quizDir = new File("quiz");
        File[] quizList = quizDir.listFiles();

        try {
            for (File quiz : quizList) {
                FileWriter writer = new FileWriter(new File("out/" + quiz.getName()));
                Scanner scanner = new Scanner(quiz);
                while (scanner.hasNextLine()) {
                    String num = scanner.nextLine();
                    String question = scanner.nextLine();
                    String choice1 = scanner.nextLine();
                    String choice2 = scanner.nextLine();
                    String choice3 = scanner.nextLine();
                    String choice4 = scanner.nextLine();

                    writer.write(num + " " + question + "\n");
                    writer.write(" 1. " + choice1 + "\n");
                    writer.write(" 2. " + choice2 + "\n");
                    writer.write(" 3. " + choice3 + "\n");
                    writer.write(" z4. " + choice4 + "\n");
                    writer.write("\n\n");
                }

                writer.flush();
                writer.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
